#!/bin/sh
#
# Run script for solarlog2mqtt
#
# (c) André Deuerling, 2025
#

. venv/bin/activate

export PYTHONPATH="$(cd "$(dirname "$0")" && pwd)/src${PYTHONPATH:+:$PYTHONPATH}"

exec /usr/bin/env python -m solarlog2mqtt "$@"
